//
// Created by yingzi on 2017/10/6.
//

#ifndef IOTEVENTMONITORPLATFORM_CONSTSTYLE_H
#define IOTEVENTMONITORPLATFORM_CONSTSTYLE_H

const int MAIN_WINDOW_WIDTH = 1000;
const int MAIN_WINDOW_HEIGHT = 600;

const int MAIN_TAB_HEIGHT = 40;

const int SUB_TAB_WIDTH = 100;
const int SUB_TAB_HEIGHT = 40;

const int EVENT_TAB_WIDTH = 100;
const int EVENT_TAB_HEIGHT = 40;

const int STATE_TAB_WIDTH = 100;
const int STATE_TAB_HEIGHT = 40;

const int CIRCLE_RADIUS = 100;

#endif //IOTEVENTMONITORPLATFORM_CONSTSTYLE_H
